### ISSUE TITLE
Add playlist to Music_Player Project

### ISSUE THREAD

**Issue by CodingBlood** [MSCKIIT/MSCxHacktoberfest#109]
In this issue, we require you to do as follows

- [x] Create a playlist folder
- [x] Add 5 decent songs to playlist folder

**Comment by nishant-giri** [comment]
Kindly assign me this issue.

**Comment by nishant-giri** [comment]
Kindly assign me this task.

**Comment by nishant-giri** [comment]
The task has been completed.
