### ISSUE TITLE
Login feature doesnt work when button pressed after entering email id (Beginner Javascript Quiz)

### ISSUE THREAD

**Issue by innatepanda** [MSCKIIT/MSCxHacktoberfest#125]
**Describe the bug**
Login feature doesnt work when button pressed after entering email id and doesnt take us to the next page.

**To Reproduce**
1. Open up index.html in live preview
2. Enter email in text input field
3. Click on login button

After this, the next page, ie homepage.html should be displayed, but that is not the case. 

**Expected behavior**
At login, the email should be stored in localstorage and the same should be displayed in the next page, which should be homepage.html

**Comment by camperjett** [comment]
please assign me to this

**Comment by innatepanda** [comment]
Assigned to @camperjett

**Comment by MuhammadTanveer94** [comment]
@innatepanda  please assign me this?

**Comment by camperjett** [comment]
@innatepanda I have fixed the issue. In continuation, I have found a few more issue(s) in Beginner Javascript Quiz directory. Should I fix them too?

**Comment by innatepanda** [comment]
@camperjett Push it first, so the issue is closed. You may proceed then. Mention the problems so I may create issues for the same.

@MuhammadTanveer94 I'm afraid this issue has been solved already.

**Comment by camperjett** [comment]
I pushed the changes

**Comment by innatepanda** [comment]
Thanks to @camperjett for solving this issue. This is now closed.
