### ISSUE TITLE
Add border and styling to the text output area (YourTextSite project)

### ISSUE THREAD

**Issue by mayankjain25** [MSCKIIT/MSCxHacktoberfest#128]
# Proposed Change
Add styling to the text output area

# Why is this important
To make sure the text preview is distinctly available

# Which tech stack does it require?
* [x] HTML and CSS
* [x] React.js

# Screenshot where change needs to be done:

![image](https://user-images.githubusercontent.com/81245278/135716524-c846711f-eb01-4ce4-a733-805d8f4f55f1.png)

**Comment by wh1zk1d** [comment]
Hi, can I work on that?

**Comment by MuhammadTanveer94** [comment]
@mayankjain25 could you please assign me this?

**Comment by mayankjain25** [comment]
> @mayankjain25 could you please assign me this?

@MuhammadTanveer94 Since @wh1zk1d asked first, it was assigned to him. Kindly contribute to other open issues for now. Apologies for the inconvenience.

**Comment by wh1zk1d** [comment]
@mayankjain25 I created a PR (#137), could you please check it?
