### ISSUE TITLE
Add a functionality of adding new task by pressing Enter [To-do Webpage]

### ISSUE THREAD

**Issue by SaniyaBhargav** [MSCKIIT/MSCxHacktoberfest#194]
#Proposed Change
Functionality needs to be added where pressing the enter key adds a new task.

**Comment by daksh4469** [comment]
Can you assign this issue to me? I would like to work on it.

**Comment by daksh4469** [comment]
Please review the PR #209 @SaniyaBhargav.

**Comment by daksh4469** [comment]
Please review the PR #213 @SaniyaBhargav.
