### ISSUE TITLE
Add in a button to make the text input and text output bold [YourTextSite project]

### ISSUE THREAD

**Issue by mayankjain25** [MSCKIIT/MSCxHacktoberfest#206]
# Proposed Change

Add in a small 'B' button, which when clicked, will make the text input and output **bold**

# Which tech stack does it require?
* [ ] HTML & CSS

Include screenshots

**Comment by moazfarrukh** [comment]
can this be assigned to me?

**Comment by Thunderbolt9** [comment]
please assign this issue to me. I have created multiple projects using HTML and CSS. Also, this will give me some experience in open source.

**Comment by RahulRudra81** [comment]
Hi can you assign this to me i can do this in much better way and i have done many project related to html css and javascript.Also i can improve the css part

**Comment by moazfarrukh** [comment]
done #219 awaiting review
