### ISSUE TITLE
Add Responsiveness in Scientific-Calculator Project

### ISSUE THREAD

**Issue by shreya0204** [MSCKIIT/MSCxHacktoberfest#216]
**Describe the bug**

In the scientific calculator project add mobile-friendly responsiveness.

**Comment by ritwik3856** [comment]
i can improve the interface & also make it responsive . please assign this to me!!!

**Comment by deepak-chouhan** [comment]
Hey, Can you assign this to me please

**Comment by shreya0204** [comment]
@ritwik3856 okay go ahead.

**Comment by shreya0204** [comment]
> Hey, Can you assign this to me please

Ritwik is working on the issue. If there isn't any response from his side within 14 days you can take up the issue.

**Comment by ritwik3856** [comment]
You won’t need to wait for long just give me 24 hr 😌.

**Comment by shreya0204** [comment]
> You won’t need to wait for long just give me 24 hr 😌.

Amazing ^_^
