### ISSUE TITLE
Several Deprecated Packages in Pubspec.yaml needs to be upgraded in KnowU Personality Test App.

### ISSUE THREAD

**Issue by bhask4r** [MSCKIIT/MSCxHacktoberfest#224]
Would be nice if all the deprecated packages are fixed.

**To Reproduce**
1. Go to 'lib folder in KnowU Persoanlity App'
2. Click on 'pubspec.yaml'
3. Update every package to newer one.
4. Make sure building the app does not make any errors.

**Expected behavior**
The app should run without any errors with latest packages.

**Comment by mk1107** [comment]
Hi, Can you assign this task to me

**Comment by samyakjain26** [comment]
Hello, Can you assign this issue to me

**Comment by mk1107** [comment]
Hi, made a PR #245  please merge it.
