### ISSUE TITLE
Name non-constant identifiers using lowerCamelCase and other dart warnings in the project in KnowU Personality Test App.

### ISSUE THREAD

**Issue by bhask4r** [MSCKIIT/MSCxHacktoberfest#225]
Simple refactoring issues for beginners to fix.

**To Reproduce**
1. Go to 'lib folder'
2. Go through every dart file
3. Check for every dart related warning.
4. Build and run project to check if it works correctly.

**Comment by sailahonkanen** [comment]
I would like to do this. Assign me please.

**Comment by mk1107** [comment]
Hi, can I work on this issue?
