### ISSUE TITLE
Change background in Calculator

### ISSUE THREAD

**Issue by SubhayanDas08** [MSCKIIT/MSCxHacktoberfest#232]
#Proposed Change

Change the background of the Calculator

#Which tech stack does it require?

* [x] Javascript
* [x] HTML and CSS

#Additional Context

**Comment by kunal-umap** [comment]
I Want to work on this , Would you please assign me this ?

**Comment by HVbajoria** [comment]
Is it the calculator repository ? If yes can you assign me this issue. I can add a gradient background to it.

**Comment by wishsagarks** [comment]
i will like to work on issue as i have prior knowledge

**Comment by HVbajoria** [comment]
Hello @SubhayanDas08  sorry I am new to GitHub so don't know how to accept the pr.
I have made a pull request to solve this issue and have added an extra feature. 
Could you please check and it would be really grateful if you could just guide me how to accept pr for future. 
Thank you.
