### ISSUE TITLE
Add Favicon to YourTextSite project

### ISSUE THREAD

**Issue by mayankjain25** [MSCKIIT/MSCxHacktoberfest#249]
Add Favicon to YourTextSite project.

**Comment by Prakarsh-Kaushik** [comment]
Can you assign this to me? and specify the type of favicon you need?

**Comment by mayankjain25** [comment]
> Can you assign this to me? The favicon image is the one included in the public folder of repo? (React image)

This is a text based project, meaning it applies some formatting to the input text. The current favicon is the default 'React' logo, so kindly add a favicon that is more on the lines of something text based, for instance, pen&paper, text on paper (or anything that satisfies your creativity).

**Comment by Hussain6** [comment]
Can you assign this to me?
