### ISSUE TITLE
Block Manipulation: Functionality to change X and Y coordinates not working

### ISSUE THREAD

**Issue by daksh4469** [MSCKIIT/MSCxHacktoberfest#263]
**Describe the bug**
The functionality to modify the X and Y coordinate of the block in the Block-Manipulation project is not working currently.

**To Reproduce**
1. Go to './Block-Manipulation'
2. Try dragging the range input of the X and Y coordinates.

**Expected behavior**

https://user-images.githubusercontent.com/60084414/135813764-a5baa7bc-d6ea-4952-b7b4-51a3823bee51.mp4

**Screenshots**

https://user-images.githubusercontent.com/60084414/135813392-e98682a0-4d0d-40b5-ac51-8aaadd02bd26.mp4

**Additional context**

**Comment by daksh4469** [comment]
Can someone add the required labels to this issue and assign this to me? I have already fixed this locally.

**Comment by ayshi028** [comment]
@daksh4469 assigned. Work on it.

**Comment by daksh4469** [comment]
Review the pull request #268. Hope it works.

**Comment by AnirbanBall** [comment]
@ayshi028 This issue already made u can refer https://github.com/MSCKIIT/MSCxHacktoberfest/issues/241 .So this issue should be closed

**Comment by daksh4469** [comment]
So should I transfer the pull request referencing it to the original issue?

**Comment by daksh4469** [comment]
Alright. Can you make an issue regarding this and assign it to me?

**Comment by AnirbanBall** [comment]
So u have to close the pull request 
If the one assigned wont be able to do that we can ping u

**Comment by AnirbanBall** [comment]
before filing issues check if anyone has already made

**Comment by daksh4469** [comment]
> before filing issues check if anyone has already made

Sure.

I closed the pull request. I will work on the UI and make a pull request for the same. Can you mention which issue should I reference in my following pull request regarding the UI?

**Comment by AnirbanBall** [comment]
You create a new issue like improving the Ui of block manipulation project . no one has done on it

First create issue then work on it.

**Comment by daksh4469** [comment]
Okay

**Comment by daksh4469** [comment]
@AnirbanBall I have created an issue for this #270. Can you add related labels and assign that to me?

**Comment by AnirbanBall** [comment]
tag ayshi028 mam on that post
