### ISSUE TITLE
Clicking on "ok" button on error alert takes user to next page 

### ISSUE THREAD

**Issue by innatepanda** [MSCKIIT/MSCxHacktoberfest#274]
**Beginner Javascript Quiz**

**To Reproduce**
1. Go to index.html
2. Do not enter anything in the input fields
3. Click on login. Alert opens up, click on ok
4. Next page "homepage.html:" is displayed

**Expected behavior**
Clicking ok button on alert should only remove the alert, not take the user to next page.

**Screenshots**
![image](https://user-images.githubusercontent.com/61987098/135961436-7041f430-9ef5-4376-8922-a67ec9d3d9c3.png)

**Comment by AmanRana10** [comment]
I can work on this issue.
