### ISSUE TITLE
I would like to add a Twitter clone

### ISSUE THREAD

**Issue by TanmayBhosale** [MSCKIIT/MSCxHacktoberfest#295]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
Add a full-stack twitter clone powered by react and django

**Describe alternatives you've considered**

**Additional context**

**Comment by vivekarora-02** [comment]
Hey there,
I would like to contribute towards this issue. Can ypu please assign me this issue?

ThankYou!
